### ISSUE TITLE
Class 'CreateUserDto' incorrectly extends base class 'RemoveFieldsWithType<Partial<User>, Function>'.   Property 'status' is optional in type 'CreateUserDto' but required in type 'RemoveFieldsWithType<Partial<User>, Function>'

### ISSUE THREAD

**Issue by praveendodda07** [nestjs/mapped-types#1121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

In version 2.0.0 we are getting this error. user **Partial**

### Minimum reproduction code

https://github.com/nestjs/mapped-types

### Steps to reproduce

install @nestjs/mapped-types with 2.0.0 version
User "Partial" method from it.
Getting the error like: Class 'CreateUserDto' incorrectly extends base class 'RemoveFieldsWithType<Partial<User>, Function>'.
  Property 'status' is optional in type 'CreateUserDto' but required in type 'RemoveFieldsWithType<Partial<User>, Function>'.

### Expected behavior

This error should not come.

### Package version

2.0.0

### Node.js version

14.21.3

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

**Comment by huthaifaa** [comment]
Getting the same error after upgrading to Nest10 today. Amazing work on the release, great job!
Made a small workaround by using the working version of partialtype.helper in version 1.2.

I believe it should be an easy fix from the team. Looking forward to it.

The error is caused when using a partial type, and says that the rest of the data is required, although it's a partial type.

**Comment by micalevisk** [comment]
> I believe it should be an easy fix from the team

it could be if someone provide us some code or the steps to create a repro of such issue, at least :smile_cat:

**Comment by huthaifaa** [comment]
`import { PartialType } from '@nestjs/mapped-types';
import {
  IsBoolean,
  IsEmpty,
  IsOptional,
  IsString,
} from 'class-validator';

export class SpCreateSpecializationDto {
  @IsString()
  name: string;

  @IsString()
  description?: string;


  @IsOptional()
  @IsBoolean()
  isPublished?: boolean;
}

export class SpUpdateSpecializationDto extends PartialType(
  SpCreateSpecializationDto,
) {
  @IsEmpty()
  isPublished?: boolean;

}
`

I found it can be fixed by using `omit`, like this:

`export class SpUpdateSpecializationDto extends PartialType(
  OmitType(SpCreateSpecializationDto, ['isPublished'] as const),
) {
  @IsEmpty()
  isPublished?: undefined;
}
`

This removes the error of:
`Class 'SpUpdateSpecializationDto' incorrectly extends base class 'RemoveFieldsWithType<Partial<SpCreateSpecializationDto>, Function>'.
  Property 'courseIds' is optional in type 'SpUpdateSpecializationDto' but required in type 'RemoveFieldsWithType<Partial<SpCreateSpecializationDto>, Function>'.`


I hope this is helpful.

**Comment by kamilmysliwiec** [comment]
Fixed in v2.0.1

**Comment by huthaifaa** [comment]
> Fixed in v2.0.1

Thank you so much, really a big fan of your work! LEGAND
