### ISSUE TITLE
OmitType not respecting deep  parent class after compiled to webpack

### ISSUE THREAD

**Issue by asomethings** [nestjs/mapped-types#433]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

It respects parent's class but it does not respect parent class's parent class when it's packed to webpack

## Expected behavior
It should respect every parent class

## Minimal reproduction of the problem with instructions
https://github.com/asomethings/mapped-types-webpack-bug

## What is the motivation / use case for changing the behavior?
Well, I have a lot of multiple base classes and use them extending a lot. So I hope the bug gets fixed.

## Environment

<pre><code>
Nest version: 8.0.9

 
For Tooling issues:
- Node version: 14
- Platform:  Linux Ubuntu 20.04

Others:

**Comment by kamilmysliwiec** [comment]
![image](https://user-images.githubusercontent.com/23244943/129008112-771290ae-1d97-477e-a45f-a1b6c7ddf343.png)

Tested on a pure NestJS typescript-starter and it works fine. This must be caused by your webpack configuration.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
