### ISSUE TITLE
Support for class-validator 0.14.0

### ISSUE THREAD

**Issue by rohanrajpal** [nestjs/mapped-types#933]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Updated my deps today & came across this warning

```
 WARN  Issues with peer dependencies found
apps/api
└─┬ @nestjs/mapped-types 1.2.0
  └── ✕ unmet peer class-validator@"^0.11.1 || ^0.12.0 || ^0.13.0": found 0.14.0
```

### Describe the solution you'd like

I guess we can bump up peer deps to 0.14.0 since there arent any breaking changes?

### Teachability, documentation, adoption, migration strategy

I dont think so these would be required.

### What is the motivation / use case for changing the behavior?

To support class-validator 0.14.0 and future versions

**Comment by rnkdsh** [comment]
+1

**Comment by Ilyes512** [comment]
There is already an automated (Renovate) PR: https://github.com/nestjs/mapped-types/pull/930

This PR can be closed after the above has been merged: https://github.com/nestjs/mapped-types/pull/926

@maintainers:
I guess its not as easy as just merging the PR (or otherwise it would have already happend?). Maybe someone can share some details about what might be blocking merging the dep update PR?

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/mapped-types/pull/930

**Comment by joyheron** [comment]
Hi! We're having an issue with our automated updates because this causes a conflict with the peer dependencies in our project (our renovate bot automatically updates our `class-validator` dependency to `0.14.0` which then conficts with the `^0.11.1 || ^0.12.0 || ^0.13.0` required by `mapped-types`). We would appreciate it if this could be merged and released quickly!
